"use client";

import { useEffect, useRef, useState } from "react";
import { storedFileListSchema, storedFileSchema } from "@cetem-qc/api-client/v1";
import type { StoredFile } from "@cetem-qc/api-client/v1";
import { fr } from "@cetem-qc/i18n";

const dateTimeFormatter = new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" });
const fill = (template: string, values: Record<string, string>) => Object.entries(values).reduce((text, [key, value]) => text.replace(`{${key}}`, value), template);

/** The size limit shown to the user; the server enforces it independently (usability pre-check only here). */
export const PDF_MAX_BYTES = 20 * 1024 * 1024;

export const pdfDownloadUrl = (taskId: string, fileId: string) =>
  `/api/tasks/${encodeURIComponent(taskId)}/pdf-files/${encodeURIComponent(fileId)}/content`;

export function formatFileSize(bytes: number): string {
  const number = new Intl.NumberFormat("fr-FR", { maximumFractionDigits: 1 });
  return bytes >= 1024 * 1024 ? `${number.format(bytes / (1024 * 1024))} ${fr.pdfFile.sizeUnit.mega}` : `${number.format(Math.max(1, Math.round(bytes / 1024)))} ${fr.pdfFile.sizeUnit.kilo}`;
}

/** Client-side check of the chosen file; usability only, the server validates type, size and content on its own. */
export function precheckPdf(file: { type: string; size: number }): string | null {
  if (file.type !== "application/pdf") return fr.pdfFile.wrongType;
  if (file.size > PDF_MAX_BYTES) return fr.pdfFile.tooLarge;
  return null;
}

type ReasonKey = keyof typeof fr.pdfFile.reason;
const isReasonKey = (key: string | null): key is ReasonKey => key !== null && key in fr.pdfFile.reason;

/** The French reason shown with a non-ready status; null for a ready file. */
export function reasonOf(file: StoredFile): string | null {
  switch (file.status) {
    case "rejected":
    case "quarantined":
      if (isReasonKey(file.validation.class)) return fr.pdfFile.reason[file.validation.class];
      return file.scan.result === "threat" ? fr.pdfFile.reason.threat : null;
    case "scan-failed": return fr.pdfFile.reason.unavailable;
    case "scan-pending": return fr.pdfFile.reason.pending;
    case "storage-failed": return fr.pdfFile.reason["storage-failed"];
    case "ready": return null;
  }
}

export type PdfUploadResult =
  | { kind: "stored"; file: StoredFile }
  | { kind: "refused"; message: string }
  | { kind: "failed" };

const refusalMessages: Array<[number, string, string]> = [
  [413, "FILE_TOO_LARGE", fr.pdfFile.tooLarge],
  [415, "UNSUPPORTED_FILE_TYPE", fr.pdfFile.wrongType],
  [409, "SUMMARY_NOT_CONFIRMED", fr.pdfFile.notConfirmed],
  [409, "CONFORMITY_NOT_DECIDED", fr.pdfFile.notDecided],
  [409, "FILE_ATTEMPT_CONFLICT", fr.pdfFile.attemptConflict],
  [502, "FILE_STORAGE_FAILED", fr.pdfFile.storageFailed],
  [422, "VALIDATION_FAILED", fr.pdfFile.invalid],
];

async function readResult(response: Response): Promise<PdfUploadResult> {
  if (response.status === 200 || response.status === 201) {
    const parsed = storedFileSchema.safeParse(await response.json());
    return parsed.success ? { kind: "stored", file: parsed.data } : { kind: "failed" };
  }
  const code = ((await response.json().catch(() => null)) as { error?: { code?: unknown } } | null)?.error?.code;
  const match = refusalMessages.find(([status, expected]) => status === response.status && expected === code);
  return match ? { kind: "refused", message: match[2] } : { kind: "failed" };
}

async function postOnce(taskId: string, attemptId: string, file: { name: string; bytes: ArrayBuffer }, fetcher: typeof fetch): Promise<PdfUploadResult> {
  return readResult(await fetcher(`/api/tasks/${encodeURIComponent(taskId)}/pdf-files`, {
    method: "POST",
    headers: { "content-type": "application/pdf", "x-attempt-id": attemptId, "x-file-name": encodeURIComponent(file.name), accept: "application/json" },
    body: file.bytes, cache: "no-store",
  }));
}

/**
 * Uploads one PDF. The attempt ID is generated by the caller once per click; it is reused only for the single automatic
 * retry after a transport error of that same click, so a lost response cannot store a second file.
 */
export async function uploadPdfOnServer(taskId: string, attemptId: string, file: { name: string; bytes: ArrayBuffer }, fetcher: typeof fetch = fetch): Promise<PdfUploadResult> {
  try {
    return await postOnce(taskId, attemptId, file, fetcher);
  } catch {
    try {
      return await postOnce(taskId, attemptId, file, fetcher);
    } catch {
      return { kind: "failed" };
    }
  }
}

/** The uploaded files of the task, newest first, or null when they could not be loaded. */
export async function loadPdfFiles(taskId: string, fetcher: typeof fetch = fetch): Promise<StoredFile[] | null> {
  try {
    const response = await fetcher(`/api/tasks/${encodeURIComponent(taskId)}/pdf-files`, { headers: { accept: "application/json" }, cache: "no-store" });
    if (response.status !== 200) return null;
    const parsed = storedFileListSchema.safeParse(await response.json());
    return parsed.success ? parsed.data.files : null;
  } catch {
    return null;
  }
}

export type PdfRescanResult = { kind: "rescanned"; file: StoredFile } | { kind: "refused"; message: string } | { kind: "failed" };

export async function retryPdfScanOnServer(taskId: string, fileId: string, fetcher: typeof fetch = fetch): Promise<PdfRescanResult> {
  try {
    const response = await fetcher(`/api/tasks/${encodeURIComponent(taskId)}/pdf-files/${encodeURIComponent(fileId)}/scan-retries`, { method: "POST", headers: { accept: "application/json" }, cache: "no-store" });
    if (response.status === 200) {
      const parsed = storedFileSchema.safeParse(await response.json());
      return parsed.success ? { kind: "rescanned", file: parsed.data } : { kind: "failed" };
    }
    const code = ((await response.json().catch(() => null)) as { error?: { code?: unknown } } | null)?.error?.code;
    return response.status === 409 && code === "FILE_NOT_RESCANNABLE" ? { kind: "refused", message: fr.pdfFile.notRescannable } : { kind: "failed" };
  } catch {
    return { kind: "failed" };
  }
}

export type PdfFilesSectionProps = {
  taskId: string;
  /** True when the summary is confirmed and a conformity decision is current. */
  eligible: boolean;
  files: StoredFile[];
  pending?: boolean;
  /** The file whose scan is being retried, or null. */
  rescanningId?: string | null;
  /** True once a file is selected, so the import button can be used. */
  hasSelection?: boolean;
  /** French message of the last failed or refused request, or null. */
  message?: string | null;
  onSelect?: (file: File | null) => void;
  onUpload?: () => void;
  onRescan?: (fileId: string) => void;
};

function FileItem({ taskId, file, rescanning, onRescan }: { taskId: string; file: StoredFile; rescanning: boolean; onRescan?: (fileId: string) => void }) {
  const reason = reasonOf(file);
  return <li className="insight-item pdf-file" data-status={file.status}>
    <strong>{file.fileName}</strong>
    {" — "}
    <span>{fr.pdfFile.status[file.status]}</span>
    {" · "}
    <span>{formatFileSize(file.byteSize)}</span>
    {" · "}
    <span>{fill(fr.pdfFile.uploadedAt, { date: dateTimeFormatter.format(new Date(file.uploadedAt)) })}</span>
    {" · "}
    <span>{fill(fr.pdfFile.uploadedBy, { name: file.uploadedBy.displayName })}</span>
    {reason && <>{" · "}<span className="field-hint">{reason}</span></>}
    {file.scan.result === "not-performed" && <>{" · "}<span className="field-hint">{fr.pdfFile.scanNote}</span></>}
    {file.status === "ready" && <>{" · "}<a href={pdfDownloadUrl(taskId, file.id)} download>{fr.pdfFile.download}</a></>}
    {(file.status === "scan-failed" || file.status === "scan-pending") && <>
      {" · "}
      <button className="secondary-button" type="button" disabled={rescanning} aria-busy={rescanning} onClick={() => onRescan?.(file.id)}>
        {rescanning ? fr.pdfFile.rescanning : fr.pdfFile.rescan}
      </button>
    </>}
  </li>;
}

/** W5 « Rapport PDF manuel » area: the import control only when eligible, the files with their status, never a designation or candidate control. */
export function PdfFilesSection({ taskId, eligible, files, pending = false, rescanningId = null, hasSelection = false, message = null, onSelect, onUpload, onRescan }: PdfFilesSectionProps) {
  return <section className="evidence-report pdf-files" aria-labelledby="pdf-files-heading">
    <h3 id="pdf-files-heading">{fr.pdfFile.heading}</h3>
    {message && <p className="field-error" role="alert">{message}</p>}
    {eligible
      ? <div className="pdf-file-upload">
        <label>
          {fr.pdfFile.choose}
          <input type="file" accept="application/pdf,.pdf" disabled={pending} onChange={(event) => onSelect?.(event.target.files?.[0] ?? null)} />
        </label>
        <p className="field-hint">{fr.pdfFile.hint}</p>
        <button className="secondary-button" type="button" disabled={pending || !hasSelection} aria-busy={pending} onClick={onUpload}>
          {pending ? fr.pdfFile.uploading : fr.pdfFile.upload}
        </button>
      </div>
      : <p className="field-hint">{fr.pdfFile.notEligible}</p>}
    {files.length > 0 && <ul className="report-candidate-list">
      {files.map((file) => <FileItem key={file.id} taskId={taskId} file={file} rescanning={rescanningId === file.id} onRescan={onRescan} />)}
    </ul>}
  </section>;
}

/** Holds the upload state; a file is shown only from a valid server response, and the list is read back from the server. */
export function PdfFilesPanel({ taskId, eligible, refreshKey = 0, onReloadState }: {
  taskId: string;
  eligible: boolean;
  /** Changes whenever the evidence was reloaded or the summary reopened, so the list is read again. */
  refreshKey?: number;
  /** Reloads the summary and decision state after a refused request (409). */
  onReloadState?: () => Promise<void>;
}) {
  const [files, setFiles] = useState<StoredFile[]>([]);
  const [selected, setSelected] = useState<File | null>(null);
  const [pending, setPending] = useState(false);
  const [rescanningId, setRescanningId] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const inFlight = useRef(false);
  const refresh = async () => {
    const loaded = await loadPdfFiles(taskId);
    if (loaded) setFiles(loaded);
  };
  useEffect(() => { void refresh(); }, [taskId, refreshKey]);
  const onSelect = (file: File | null) => {
    setSelected(file);
    setMessage(file ? precheckPdf(file) : null);
  };
  const onUpload = () => {
    if (inFlight.current || !selected) return;
    const refusal = precheckPdf(selected);
    if (refusal) { setMessage(refusal); return; }
    inFlight.current = true;
    setPending(true);
    setMessage(null);
    void selected.arrayBuffer()
      // A new attempt ID per click.
      .then((bytes) => uploadPdfOnServer(taskId, crypto.randomUUID(), { name: selected.name, bytes }))
      .catch((): PdfUploadResult => ({ kind: "failed" }))
      .then(async (result) => {
        if (result.kind === "stored") {
          setSelected(null);
        } else if (result.kind === "refused") {
          await onReloadState?.();
          setMessage(result.message);
        } else {
          setMessage(fr.pdfFile.internal);
        }
        await refresh();
        inFlight.current = false;
        setPending(false);
      });
  };
  const onRescan = (fileId: string) => {
    if (inFlight.current) return;
    inFlight.current = true;
    setRescanningId(fileId);
    setMessage(null);
    void retryPdfScanOnServer(taskId, fileId).then(async (result) => {
      if (result.kind === "refused") setMessage(result.message);
      else if (result.kind === "failed") setMessage(fr.pdfFile.internal);
      await refresh();
      inFlight.current = false;
      setRescanningId(null);
    });
  };
  return <PdfFilesSection taskId={taskId} eligible={eligible} files={files} pending={pending} rescanningId={rescanningId} hasSelection={selected !== null} message={message} onSelect={onSelect} onUpload={onUpload} onRescan={onRescan} />;
}
