"use client";

import { useEffect, useRef, useState } from "react";
import { officialReportSchema, reportCandidateListSchema, reportCandidateSchema } from "@cetem-qc/api-client/v1";
import type { OfficialReport, ReportCandidate } from "@cetem-qc/api-client/v1";
import { fr } from "@cetem-qc/i18n";

const dateTimeFormatter = new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" });
const fill = (template: string, values: Record<string, string>) => Object.entries(values).reduce((text, [key, value]) => text.replace(`{${key}}`, value), template);
const decisionLabel = (outcome: ReportCandidate["bindings"]["conformityOutcome"]) => outcome === "machine-conforme" ? fr.conformity.conforme : fr.conformity.nonConforme;

export const reportDownloadUrl = (taskId: string, candidateId: string) =>
  `/api/tasks/${encodeURIComponent(taskId)}/report-candidates/${encodeURIComponent(candidateId)}/file`;

export type ReportGenerateResult =
  | { kind: "generated"; candidate: ReportCandidate }
  | { kind: "generation-failed" }
  | { kind: "refused"; message: string }
  | { kind: "failed" };

const refusalMessages: Record<string, string> = {
  SUMMARY_NOT_CONFIRMED: fr.report.notConfirmed,
  CONFORMITY_NOT_DECIDED: fr.report.notDecided,
  REPORT_INPUTS_CHANGED: fr.report.inputsChanged,
  REPORT_ATTEMPT_CONFLICT: fr.report.attemptConflict,
  REPORT_OFFICIAL_DESIGNATED: fr.report.designate.officialDesignated,
};

export type ReportDesignateResult =
  | { kind: "designated"; official: OfficialReport }
  | { kind: "refused"; message: string }
  | { kind: "failed" };

const designateRefusals: Record<string, string> = {
  REPORT_CANDIDATE_NOT_READY: fr.report.designate.notReady,
  REPORT_CANDIDATE_OUTDATED: fr.report.designate.outdated,
  REPORT_ALREADY_OFFICIAL: fr.report.designate.alreadyOfficial,
};

/** Designates one candidate official. One request per click; the designation is final, so it is never retried automatically. */
export async function designateReportCandidateOnServer(taskId: string, candidateId: string, fetcher: typeof fetch = fetch): Promise<ReportDesignateResult> {
  try {
    const response = await fetcher(`/api/tasks/${encodeURIComponent(taskId)}/report-candidates/${encodeURIComponent(candidateId)}/designate`, {
      method: "POST", headers: { "content-type": "application/json", accept: "application/json" }, body: "{}", cache: "no-store",
    });
    if (response.status === 200 || response.status === 201) {
      const parsed = officialReportSchema.safeParse(await response.json());
      return parsed.success ? { kind: "designated", official: parsed.data } : { kind: "failed" };
    }
    const code = ((await response.json().catch(() => null)) as { error?: { code?: unknown } } | null)?.error?.code;
    if (response.status === 409 && typeof code === "string" && designateRefusals[code]) return { kind: "refused", message: designateRefusals[code]! };
    if (response.status === 404) return { kind: "refused", message: fr.report.designate.notFound };
    return { kind: "failed" };
  } catch {
    return { kind: "failed" };
  }
}

/** The official report of the task, or null when there is none or it could not be loaded. */
export async function loadOfficialReport(taskId: string, fetcher: typeof fetch = fetch): Promise<OfficialReport | null> {
  try {
    const response = await fetcher(`/api/tasks/${encodeURIComponent(taskId)}/official-report`, { headers: { accept: "application/json" }, cache: "no-store" });
    if (response.status !== 200) return null;
    const parsed = officialReportSchema.safeParse(await response.json());
    return parsed.success ? parsed.data : null;
  } catch {
    return null;
  }
}

async function postOnce(taskId: string, attemptId: string, fetcher: typeof fetch): Promise<ReportGenerateResult> {
  const response = await fetcher(`/api/tasks/${encodeURIComponent(taskId)}/report-candidates`, {
    method: "POST", headers: { "content-type": "application/json", accept: "application/json" }, body: JSON.stringify({ attemptId }), cache: "no-store",
  });
  if (response.status === 200 || response.status === 201) {
    const parsed = reportCandidateSchema.safeParse(await response.json());
    return parsed.success ? { kind: "generated", candidate: parsed.data } : { kind: "failed" };
  }
  const code = ((await response.json().catch(() => null)) as { error?: { code?: unknown } } | null)?.error?.code;
  if (response.status === 502 && code === "REPORT_GENERATION_FAILED") return { kind: "generation-failed" };
  if (response.status === 409 && typeof code === "string" && refusalMessages[code]) return { kind: "refused", message: refusalMessages[code]! };
  return { kind: "failed" };
}

/**
 * Requests one candidate. The attempt ID is generated by the caller once per click; it is reused only for the single
 * automatic retry after a transport error of that same click, so a lost response cannot create a second candidate.
 */
export async function generateReportCandidateOnServer(taskId: string, attemptId: string, fetcher: typeof fetch = fetch): Promise<ReportGenerateResult> {
  try {
    return await postOnce(taskId, attemptId, fetcher);
  } catch {
    try {
      return await postOnce(taskId, attemptId, fetcher);
    } catch {
      return { kind: "failed" };
    }
  }
}

/** The candidates of the task, newest first, or null when they could not be loaded. */
export async function loadReportCandidates(taskId: string, fetcher: typeof fetch = fetch): Promise<ReportCandidate[] | null> {
  try {
    const response = await fetcher(`/api/tasks/${encodeURIComponent(taskId)}/report-candidates`, { headers: { accept: "application/json" }, cache: "no-store" });
    if (response.status !== 200) return null;
    const parsed = reportCandidateListSchema.safeParse(await response.json());
    return parsed.success ? parsed.data.candidates : null;
  } catch {
    return null;
  }
}

export type ReportCandidatesSectionProps = {
  taskId: string;
  /** True when the summary is confirmed and a conformity decision is current. */
  eligible: boolean;
  candidates: ReportCandidate[];
  pending?: boolean;
  /** True after a generation failure (502): the retry button replaces the generate button. */
  failedAttempt?: boolean;
  /** French message of the last failed or refused request, or null. */
  message?: string | null;
  onGenerate?: () => void;
  /** The official report once designated: generation, retry and designation controls are then hidden. */
  official?: OfficialReport | null;
  /** The candidate waiting for the irreversible confirmation, or null. */
  confirmingId?: string | null;
  /** The candidate being designated, or null. */
  designatingId?: string | null;
  onAskDesignate?: (candidateId: string) => void;
  onCancelDesignate?: () => void;
  onConfirmDesignate?: (candidateId: string) => void;
};

function CandidateItem({ taskId, candidate, official, confirming, designating, anyDesignating, onAskDesignate, onCancelDesignate, onConfirmDesignate }: {
  taskId: string; candidate: ReportCandidate; official: OfficialReport | null; confirming: boolean; designating: boolean; anyDesignating: boolean;
  onAskDesignate?: (candidateId: string) => void; onCancelDesignate?: () => void; onConfirmDesignate?: (candidateId: string) => void;
}) {
  return <li className="insight-item report-candidate" data-status={candidate.status}>
    <strong>{fr.report.candidateBadge}</strong>
    {" · "}
    <span>{candidate.origin === "uploaded-pdf" ? fr.report.origin.uploadedPdf : fr.report.origin.generatedWord}</span>
    {" — "}
    <span>{fr.report.status[candidate.status]}</span>
    {" · "}
    <span>{fill(fr.report.requestedAt, { date: dateTimeFormatter.format(new Date(candidate.requestedAt)) })}</span>
    {" · "}
    <span>{fill(fr.report.requestedBy, { name: candidate.requestedBy.displayName })}</span>
    {" · "}
    <span>{fill(fr.report.summaryVersion, { n: String(candidate.bindings.summaryVersion) })}</span>
    {" · "}
    <span>{fill(fr.report.decision, { label: decisionLabel(candidate.bindings.conformityOutcome) })}</span>
    {candidate.source?.scanResult === "not-performed" && <>{" · "}<span className="field-hint">{fr.pdfFile.scanNote}</span></>}
    {candidate.status === "official" && official && official.candidateId === candidate.id && <>
      {" · "}<span>{fill(fr.report.designate.designatedBy, { name: official.designatedBy.displayName })}</span>
      {" "}<span>{fill(fr.report.designate.designatedAt, { date: dateTimeFormatter.format(new Date(official.designatedAt)) })}</span>
    </>}
    {candidate.file && (candidate.status === "ready" || candidate.status === "outdated" || candidate.status === "official" || candidate.status === "superseded")
      ? <>{" · "}<a href={reportDownloadUrl(taskId, candidate.id)} download>{fr.report.download}</a></>
      : null}
    {candidate.status === "ready" && !official && !confirming && !designating && <>
      {" · "}
      <button className="secondary-button" type="button" disabled={anyDesignating} onClick={() => onAskDesignate?.(candidate.id)}>{fr.report.designate.button}</button>
    </>}
    {candidate.status === "ready" && !official && (confirming || designating) && <div className="field-hint" role="group" aria-label={fr.report.designate.button}>
      <p>{fr.report.designate.prompt}</p>
      <button className="primary-button" type="button" disabled={designating} aria-busy={designating} onClick={() => onConfirmDesignate?.(candidate.id)}>
        {designating ? fr.report.designate.pending : fr.report.designate.confirm}
      </button>
      {" "}
      <button className="secondary-button" type="button" disabled={designating} onClick={onCancelDesignate}>{fr.report.designate.cancel}</button>
    </div>}
  </li>;
}

/** W5 report area: the generate button only when eligible and no official report exists, the list of candidates, the designation control only on ready candidates. */
export function ReportCandidatesSection({ taskId, eligible, candidates, pending = false, failedAttempt = false, message = null, onGenerate, official = null, confirmingId = null, designatingId = null, onAskDesignate, onCancelDesignate, onConfirmDesignate }: ReportCandidatesSectionProps) {
  return <section className="evidence-report" aria-labelledby="evidence-report-heading">
    <h3 id="evidence-report-heading">{fr.report.heading}</h3>
    {message && <p className="field-error" role="alert">{message}</p>}
    {official
      ? null
      : eligible
        ? <button className="secondary-button" type="button" disabled={pending || designatingId !== null} aria-busy={pending} onClick={onGenerate}>
          {pending ? fr.report.generating : failedAttempt ? fr.report.retry : fr.report.generate}
        </button>
        : <p className="field-hint">{fr.report.notEligible}</p>}
    {candidates.length > 0 && <ul className="report-candidate-list">
      {candidates.map((candidate) => <CandidateItem key={candidate.id} taskId={taskId} candidate={candidate} official={official}
        confirming={confirmingId === candidate.id} designating={designatingId === candidate.id} anyDesignating={designatingId !== null}
        onAskDesignate={onAskDesignate} onCancelDesignate={onCancelDesignate} onConfirmDesignate={onConfirmDesignate} />)}
    </ul>}
  </section>;
}

/** Holds the request state; a candidate is shown only from a valid server response, and the list is read back from the server. */
export function ReportCandidatesPanel({ taskId, eligible, refreshKey = 0, onReloadState }: {
  taskId: string;
  eligible: boolean;
  /** Changes whenever the evidence was reloaded or the summary reopened, so the derived statuses are read again. */
  refreshKey?: number;
  /** Reloads the summary and decision state after a refused request (409). */
  onReloadState?: () => Promise<void>;
}) {
  const [candidates, setCandidates] = useState<ReportCandidate[]>([]);
  const [pending, setPending] = useState(false);
  const [failedAttempt, setFailedAttempt] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [official, setOfficial] = useState<OfficialReport | null>(null);
  const [confirmingId, setConfirmingId] = useState<string | null>(null);
  const [designatingId, setDesignatingId] = useState<string | null>(null);
  const inFlight = useRef(false);
  const refresh = async () => {
    const loaded = await loadReportCandidates(taskId);
    if (loaded) setCandidates(loaded);
    const loadedOfficial = await loadOfficialReport(taskId);
    if (loadedOfficial) setOfficial(loadedOfficial);
  };
  useEffect(() => { void refresh(); }, [taskId, refreshKey]);
  const onGenerate = () => {
    if (inFlight.current) return;
    inFlight.current = true;
    setPending(true);
    setMessage(null);
    // A new attempt ID per click, and per « Réessayer ».
    void generateReportCandidateOnServer(taskId, crypto.randomUUID()).then(async (result) => {
      if (result.kind === "generated") {
        setFailedAttempt(false);
      } else if (result.kind === "generation-failed") {
        setFailedAttempt(true);
        setMessage(fr.report.failed);
      } else if (result.kind === "refused") {
        setFailedAttempt(false);
        await onReloadState?.();
        setMessage(result.message);
      } else {
        setMessage(fr.report.internal);
      }
      await refresh();
      inFlight.current = false;
      setPending(false);
    });
  };
  const onConfirmDesignate = (candidateId: string) => {
    if (inFlight.current) return;
    inFlight.current = true;
    setDesignatingId(candidateId);
    setMessage(null);
    void designateReportCandidateOnServer(taskId, candidateId).then(async (result) => {
      if (result.kind === "designated") {
        setOfficial(result.official);
      } else if (result.kind === "refused") {
        await onReloadState?.();
        setMessage(result.message);
      } else {
        setMessage(fr.report.designate.internal);
      }
      await refresh();
      setConfirmingId(null);
      inFlight.current = false;
      setDesignatingId(null);
    });
  };
  return <ReportCandidatesSection taskId={taskId} eligible={eligible} candidates={candidates} pending={pending} failedAttempt={failedAttempt} message={message} onGenerate={onGenerate}
    official={official} confirmingId={confirmingId} designatingId={designatingId} onAskDesignate={(id) => { setMessage(null); setConfirmingId(id); }}
    onCancelDesignate={() => setConfirmingId(null)} onConfirmDesignate={onConfirmDesignate} />;
}
