"use client";

import { useEffect, useRef, useState } from "react";
import { reportCandidateListSchema, reportCandidateSchema } from "@cetem-qc/api-client/v1";
import type { ReportCandidate } from "@cetem-qc/api-client/v1";
import { fr } from "@cetem-qc/i18n";

const dateTimeFormatter = new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" });
const fill = (template: string, values: Record<string, string>) => Object.entries(values).reduce((text, [key, value]) => text.replace(`{${key}}`, value), template);
const decisionLabel = (outcome: ReportCandidate["bindings"]["conformityOutcome"]) => outcome === "machine-conforme" ? fr.conformity.conforme : fr.conformity.nonConforme;

export const reportDownloadUrl = (taskId: string, candidateId: string) =>
  `/api/tasks/${encodeURIComponent(taskId)}/report-candidates/${encodeURIComponent(candidateId)}/file`;

export type ReportGenerateResult =
  | { kind: "generated"; candidate: ReportCandidate }
  | { kind: "generation-failed" }
  | { kind: "refused"; message: string }
  | { kind: "failed" };

const refusalMessages: Record<string, string> = {
  SUMMARY_NOT_CONFIRMED: fr.report.notConfirmed,
  CONFORMITY_NOT_DECIDED: fr.report.notDecided,
  REPORT_INPUTS_CHANGED: fr.report.inputsChanged,
  REPORT_ATTEMPT_CONFLICT: fr.report.attemptConflict,
};

async function postOnce(taskId: string, attemptId: string, fetcher: typeof fetch): Promise<ReportGenerateResult> {
  const response = await fetcher(`/api/tasks/${encodeURIComponent(taskId)}/report-candidates`, {
    method: "POST", headers: { "content-type": "application/json", accept: "application/json" }, body: JSON.stringify({ attemptId }), cache: "no-store",
  });
  if (response.status === 200 || response.status === 201) {
    const parsed = reportCandidateSchema.safeParse(await response.json());
    return parsed.success ? { kind: "generated", candidate: parsed.data } : { kind: "failed" };
  }
  const code = ((await response.json().catch(() => null)) as { error?: { code?: unknown } } | null)?.error?.code;
  if (response.status === 502 && code === "REPORT_GENERATION_FAILED") return { kind: "generation-failed" };
  if (response.status === 409 && typeof code === "string" && refusalMessages[code]) return { kind: "refused", message: refusalMessages[code]! };
  return { kind: "failed" };
}

/**
 * Requests one candidate. The attempt ID is generated by the caller once per click; it is reused only for the single
 * automatic retry after a transport error of that same click, so a lost response cannot create a second candidate.
 */
export async function generateReportCandidateOnServer(taskId: string, attemptId: string, fetcher: typeof fetch = fetch): Promise<ReportGenerateResult> {
  try {
    return await postOnce(taskId, attemptId, fetcher);
  } catch {
    try {
      return await postOnce(taskId, attemptId, fetcher);
    } catch {
      return { kind: "failed" };
    }
  }
}

/** The candidates of the task, newest first, or null when they could not be loaded. */
export async function loadReportCandidates(taskId: string, fetcher: typeof fetch = fetch): Promise<ReportCandidate[] | null> {
  try {
    const response = await fetcher(`/api/tasks/${encodeURIComponent(taskId)}/report-candidates`, { headers: { accept: "application/json" }, cache: "no-store" });
    if (response.status !== 200) return null;
    const parsed = reportCandidateListSchema.safeParse(await response.json());
    return parsed.success ? parsed.data.candidates : null;
  } catch {
    return null;
  }
}

export type ReportCandidatesSectionProps = {
  taskId: string;
  /** True when the summary is confirmed and a conformity decision is current. */
  eligible: boolean;
  candidates: ReportCandidate[];
  pending?: boolean;
  /** True after a generation failure (502): the retry button replaces the generate button. */
  failedAttempt?: boolean;
  /** French message of the last failed or refused request, or null. */
  message?: string | null;
  onGenerate?: () => void;
};

function CandidateItem({ taskId, candidate }: { taskId: string; candidate: ReportCandidate }) {
  return <li className="insight-item report-candidate" data-status={candidate.status}>
    <strong>{fr.report.candidateBadge}</strong>
    {" — "}
    <span>{fr.report.status[candidate.status]}</span>
    {" · "}
    <span>{fill(fr.report.requestedAt, { date: dateTimeFormatter.format(new Date(candidate.requestedAt)) })}</span>
    {" · "}
    <span>{fill(fr.report.requestedBy, { name: candidate.requestedBy.displayName })}</span>
    {" · "}
    <span>{fill(fr.report.summaryVersion, { n: String(candidate.bindings.summaryVersion) })}</span>
    {" · "}
    <span>{fill(fr.report.decision, { label: decisionLabel(candidate.bindings.conformityOutcome) })}</span>
    {candidate.file && (candidate.status === "ready" || candidate.status === "outdated")
      ? <>{" · "}<a href={reportDownloadUrl(taskId, candidate.id)} download>{fr.report.download}</a></>
      : null}
  </li>;
}

/** W5 report area: the generate button only when eligible, the list of candidates, never a designation or upload control. */
export function ReportCandidatesSection({ taskId, eligible, candidates, pending = false, failedAttempt = false, message = null, onGenerate }: ReportCandidatesSectionProps) {
  return <section className="evidence-report" aria-labelledby="evidence-report-heading">
    <h3 id="evidence-report-heading">{fr.report.heading}</h3>
    {message && <p className="field-error" role="alert">{message}</p>}
    {eligible
      ? <button className="secondary-button" type="button" disabled={pending} aria-busy={pending} onClick={onGenerate}>
        {pending ? fr.report.generating : failedAttempt ? fr.report.retry : fr.report.generate}
      </button>
      : <p className="field-hint">{fr.report.notEligible}</p>}
    {candidates.length > 0 && <ul className="report-candidate-list">
      {candidates.map((candidate) => <CandidateItem key={candidate.id} taskId={taskId} candidate={candidate} />)}
    </ul>}
  </section>;
}

/** Holds the request state; a candidate is shown only from a valid server response, and the list is read back from the server. */
export function ReportCandidatesPanel({ taskId, eligible, refreshKey = 0, onReloadState }: {
  taskId: string;
  eligible: boolean;
  /** Changes whenever the evidence was reloaded or the summary reopened, so the derived statuses are read again. */
  refreshKey?: number;
  /** Reloads the summary and decision state after a refused request (409). */
  onReloadState?: () => Promise<void>;
}) {
  const [candidates, setCandidates] = useState<ReportCandidate[]>([]);
  const [pending, setPending] = useState(false);
  const [failedAttempt, setFailedAttempt] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const inFlight = useRef(false);
  const refresh = async () => {
    const loaded = await loadReportCandidates(taskId);
    if (loaded) setCandidates(loaded);
  };
  useEffect(() => { void refresh(); }, [taskId, refreshKey]);
  const onGenerate = () => {
    if (inFlight.current) return;
    inFlight.current = true;
    setPending(true);
    setMessage(null);
    // A new attempt ID per click, and per « Réessayer ».
    void generateReportCandidateOnServer(taskId, crypto.randomUUID()).then(async (result) => {
      if (result.kind === "generated") {
        setFailedAttempt(false);
      } else if (result.kind === "generation-failed") {
        setFailedAttempt(true);
        setMessage(fr.report.failed);
      } else if (result.kind === "refused") {
        setFailedAttempt(false);
        await onReloadState?.();
        setMessage(result.message);
      } else {
        setMessage(fr.report.internal);
      }
      await refresh();
      inFlight.current = false;
      setPending(false);
    });
  };
  return <ReportCandidatesSection taskId={taskId} eligible={eligible} candidates={candidates} pending={pending} failedAttempt={failedAttempt} message={message} onGenerate={onGenerate} />;
}
